---
# yamllint disable rule:line-length
name: prepare_repository_bullseye

concurrency: build

on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [trigger_build]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pvelati/docker-debian-repo-mgmt:main
    steps:
      - name: Print variables from POST
        run: |
          echo "codename -> ${{ github.event.client_payload.repository.codename }}"
          echo "owner    -> ${{ github.event.client_payload.repository.owner }}"
          echo "name     -> ${{ github.event.client_payload.repository.name }}"
          echo "tag      -> ${{ github.event.client_payload.repository.tag }}"

      - uses: actions/checkout@v3

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Download latest deb files
        run: |
          curl \
           -s https://api.github.com/repos/${{ github.event.client_payload.repository.name }}/releases/tags/${{ github.event.client_payload.repository.tag }} \
           | jq -r ".assets[] | select(.name | test(\"deb\")) | .browser_download_url" | xargs -P16 wget -P tmp

      - name: Create repo structure
        run: |
          reprepro -b debian includedeb ${{ github.event.client_payload.repository.codename }} tmp/*.deb

      - name: Check if there is any new files
        id: verify_diff
        run: |
          git diff --quiet || echo "::set-output name=new_files::true"

      - name: Commit files
        if: steps.verify_diff.outputs.new_files == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add debian
          git commit -m "bot: update packages"
          git push
# yamllint enable rule:line-length
